### ISSUE TITLE
Beer Blender Bar | Auswahl entfernen der ingredients optimieren

### ISSUE THREAD

**Issue by papulla** [wol-soft/beerplop-issues#10]
Wenn ich die Items auswählen/entfernen will, muss ich diese Umständlich hinein/heraus schieben.
Das führt manchmal dazu, das die Items nicht richtig rein bzw. rausgeschoben werden.
Sehr ärgerlich, wenn es mal schnell gehen muss.
Mein Vorschlag:
- Item entfernen/hinzufügen mit rechten Mausklick oder Doppelklick
- ein Item kann nur hinzugefügt werden, wenn noch ein Slot frei ist

**Comment by wol-soft** [comment]
Implemented double click to equip/unequip Beer Blender Bar ingredients with version 1.40.0
