### ISSUE TITLE
Slider sollen aufeinander reagieren

### ISSUE THREAD

**Issue by papulla** [wol-soft/beerplop-issues#12]
Wenn ich einen Slider erhöhe, soll er automatisch bei einem anderen den Wert runter setzen.

**Comment by wol-soft** [comment]
Die Frage ist, wie er entscheiden soll, bei welchem Slider er den Wert runtersetzt. Es können ja (theoretisch) bis zu zehn Slider gleichzeitig aktiv sein, wenn man entsprechend viele Projects am Laufen hat und alle Slider auf 10% einstellt.

**Comment by papulla** [comment]
Hauptsächlich geht es um das zusammenspiel zwischen der Beer Bank und den Researches.
Würde sagen, dass die Beer Bank die Researches verringert und umgekehrt.
Meist hat man nur einen Research. Also nur ein Research und Beer Bank.

**Comment by Jared87** [comment]
Ich würde sobald die Gesamtsumme der Slider >100 ist die % anhand der Basis der Summe berechnen. Wenn 2 auf 100 sind, bekommen beide 50

**Comment by Jared87** [comment]
Mal ein wenig ausführlicher:

Ein Slider ist aktiv bei 100%. => 100% der Plops laufen hier rein.
Wird nun ein 2. Slider auf 25% gesetzt wird nicht mehr 100 als Basis genommen sondern 125. Es laufen nun 80% in den ersten und 20% in den 2. Slider. 

So lange die Summe < 100 ist, ist 100 die Basis und der Rest läuft in die Plops. 

2 Slider sind bei 25%, beide bekommen 25% und 50% laufen in die Plops. (Basis 100)
2 Slider sind bei 50% beide bekommen 50% und nichts läuft in die Plops. (Basis 100)
2 Slider sind bei 75% beide bekommen 50%  und nichts läuft in die Plops. (Basis 150)

**Comment by wol-soft** [comment]
@papulla @Jared87 

Ich denke das Verhalten wäre dann trotzdem ziemlich strange für den Benutzer.

Man hat zB. ein research Project auf 50% und die Beer Bank auf 50%. Nun ändert man den Slider an der Beer Bank auf 100%, dann greift die Berechnung mit der Basis 150, dann bekommt (weil es ja auf 10er Schritte festgelegt ist und dementsprechend gerundet werden muss) das Research Project 30% und die Bank springt auf 70% zurück. Nun stellt man es noch mal auf 100%, dann ist die Basis also 130%. Das Research Project springt dann auf 20% und die Bank auf 80%. Apiel wiederholen, Bank auf 100% schrauben. Research Project springt auf 10%, Bank auf 90%. Ab da ist man gelockt. Man kann die Bank so oft wie man will auf 100% stellen, es wird immer auf 90% zurückspringen. 

Da hätte ich als User nicht das Gefühl, zu verstehen, was da passiert. Es sieht buggy aus, wenn die Slider willkürlich hin und herspringen.

**Comment by papulla** [comment]
Ne, sollen auch nur beim hochmarkieren bei den anderen runter gehen.
Also wenn ich in der Beer Bank höher mache, soll er bei den researches runter gehen, wenn dort was gesetzt ist und umgekehrt, wenn ich bei einem Research hoch mache, dann soll er bei Beer Bank runter gehen.
Nichts rauf, nur runter im zusammenspiel zwischen research und beer bank. Mehr nicht.

**Comment by Marcnesium87** [comment]
Alternativ: Checkbox die das Verschieben der Slider über den Verfügbaren Rest % erlaubt. Alle offenen Slider werden dann auf 0% gesetzt, egal um wieviel der gerade aktive Slider verändert wird.
Beispiel:
Research1: 20%
Research2: 40%
Research3: 20%

Ich kann jetzt 20% in die Beerbank geben, bei deaktivierter Checkbox "Allow Overfading" ist bei 20% Schluss. Bei aktivierter Checkbox, kann ich den Slider über die 20% ziehen, alle offnen Slider (Research1-3) fallen sofort auf 0%.
Die Anwendung betrifft ja meißt nur den Fall das ich aufgrund eines Buffs, schnell auf Research switchen will, mir ist es daher egal ob die anderen Slider auf 0% fallen.

**Comment by wol-soft** [comment]
Gefällt mir persönlich auch deutlich besser, da die Mechanik verständlicher ist. Wenn man einen Slider hochstellt werden die anderen Slider runtergestellt. Meistens wird man den entsprechenden Slider dann ja eh auf 100% stellen wollen.

Irgendwelche wilden Berechnungen im Hintergrund machen es meiner Meinung nach nur komplizierter für den Spieler (und wahrscheinlich auch Fehleranfälliger)

**Comment by wol-soft** [comment]
Option zum Einschalten der Slider-Interaktion mit 1.51.0 releast. Default ist weiterhin, dass man nicht höher als Summe aller Slider = 100% einstellen kann.
