### ISSUE TITLE
Neue Upgrade Paths für Beer Factories

### ISSUE THREAD

**Issue by KingKatzi** [wol-soft/beerplop-issues#15]

**Comment by wol-soft** [comment]
@KingKatzi gibt es Pfade, die deiner Meinung nach besonders wichtig wären?

**Comment by KingKatzi** [comment]
Z.B. Lumberjack, Transport System, Precious Mine und sowas wie die Engineers wäre auch cool :)

**Comment by Jared87** [comment]
Senken des Verbrauchs von Extensions

**Comment by wol-soft** [comment]
Gibt immerhin mit 1.41.0 schon mal wieder zwei neue Upgrades für die Academy. 

Generell vermutlich ein schwieriger Issue, wann kann man den schließen? Man kann ja immer weiter neue Upgrades hinzufügen.

**Comment by wol-soft** [comment]
Mit Version 1.44.0 wurden insgesamt 30 neue Upgrade-Pfade hinzugefügt.
