### ISSUE TITLE
Clonedike: Unterschied in der Beschreibung

### ISSUE THREAD

**Issue by sirtapps** [wol-soft/beerplop-issues#16]
Im Hover bei der Forschung steht "Beer Cloner are 20% stronger" und im Hover bei einem Gebäude steht "Boosted by 15%".

**Comment by wol-soft** [comment]
Der korrekte Wert ist 15%, habe es von 20% runtergesetzt und die Labels nicht angepasst. Korrigiere ich mit der kommenden Version.
Danke für den aufmerksamen Hinweis!
