### ISSUE TITLE
Manche Achievements nicht erhalten, obwohl schon fertig

### ISSUE THREAD

**Issue by papulla** [wol-soft/beerplop-issues#19]
Achievement Giza Completed und 50 Magier trainiert steht auf not reached.
Beides habe ich eigentlich schon erreicht, aber nicht das Achievement erhalten.
Ich schätze mal, die Giza habe ich noch ncht erhalten, da ich mit der schon fertig war, bevor das Achievement vorhanden war.
Habe das 50 Magier erhalten, als ich einen neuen gekauft und der zum Auto-Training geschickt wurde.

**Comment by papulla** [comment]
![image](https://user-images.githubusercontent.com/51719679/59567558-8cd43d80-906f-11e9-911d-18bd9bdb5df3.png)

**Comment by papulla** [comment]
![image](https://user-images.githubusercontent.com/51719679/59567576-dde43180-906f-11e9-8945-463eb2d9b5a8.png)

**Comment by wol-soft** [comment]
@papulla zum giza habe ich mit 1.36.0 nen Fix gebaut, vielleicht hattest du das schon worher. Ich checke das noch mal. Werde nen Update-Check einbauen, der es freischaltet, wenn man den Unique Build abgeschlossen hat.

Das für 50 Magicians ist relativ neu, du hast seitdem vermutlich keinen neuen Magier gekauft, um den Check anzutriggern.

**Comment by wol-soft** [comment]
@papulla, 1.43.0 ist releast. Du solltest das giza-Achievement erhalten haben. Wenn ja, Issue bitte schließen.

**Comment by papulla** [comment]
![image](https://user-images.githubusercontent.com/51719679/60126600-a7549800-978e-11e9-9a28-fc71994e1f9a.png)

**Comment by papulla** [comment]
Leider nicht

**Comment by wol-soft** [comment]
@papulla was kommt dabei raus, wenn du in der Konsole

```js
(new Minigames.BeerFactory()).uniqueBuild.state.builds.giza.buildFinished;
```
und
```js
(new Beerplop.AchievementController()).getAchievementStorage().achievements.beerFactory.uniqueBuild.completed.giza;
```
ausführst?

**Comment by papulla** [comment]
(new Minigames.BeerFactory()).uniqueBuild.state.builds.giza.buildFinished;
Wed May 01 2019 21:47:35 GMT+0200 (Mitteleuropäische Sommerzeit)

(new Beerplop.AchievementController()).getAchievementStorage().achievements.beerFactory.uniqueBuild.completed.giza;
[
key: "beerFactory.uniqueBuild.completed.giza"
reached: false
}

**Comment by papulla** [comment]
Hab das checkAchievement dazu selber ausgeführt.
