### ISSUE TITLE
Service assistant discount limit to 6%?

### ISSUE THREAD

**Issue by sirtapps** [wol-soft/beerplop-issues#2]
I have >750 Service Assistant but discount is still 6%.

**Comment by wol-soft** [comment]
Hi @sirtapps,

the Service Assistant discount is capped at 10%. The speed it increases just slows doen after reaching a 5% discount. I've documented the behaviour in the wiki: [Service Assistant discount](https://wol-soft.de/apps/beerplop/wiki/index.php/Buildings#Upgrade:_Help_me_to_build_it_up)

Thanks for pointing out, it's nowhere apparent.

Cheers 🍺
