### ISSUE TITLE
Research Projects durch Klicken pushen

### ISSUE THREAD

**Issue by papulla** [wol-soft/beerplop-issues#20]
Schön wäre es, wenn man die jeweiligen Research Projects durch Klicken auf deren Symbol pushen könnte analog zu den Beer Plops.

**Comment by wol-soft** [comment]
Da es sich bei den Research Projects um passive Spielelemente handelt, die nicht aktiv bespielt werden, sehe ich dieses Feature als nicht zielführend an.

**Comment by wol-soft** [comment]
Not implemented
