### ISSUE TITLE
Neue Academy Upgrades

### ISSUE THREAD

**Issue by papulla** [wol-soft/beerplop-issues#21]
Upgrades in mehreren Stufen, um die Produktion und Lagermenge von

- Marble
- Tools
- Charcoal
- Medallions

zu erhöhen.

**Comment by wol-soft** [comment]
Duplicate of #15

**Comment by wol-soft** [comment]
Mit Version 1.44.0 wurden insgesamt 30 neue Upgrade-Pfade hinzugefügt. Darin sind Storage-Erweiterungen und auch Upgrades um die Extension-Produktion zu erhöhen enthalten.
