### ISSUE TITLE
Negative Produktion

### ISSUE THREAD

**Issue by sirtapps** [wol-soft/beerplop-issues#23]
![grafik](https://user-images.githubusercontent.com/21241313/60345785-0d713300-99ba-11e9-89b1-0899a22d856d.png)

Nach dem Update für die Verdopplung der Tool-Produktion bekomme ich manchmal negative Lagerwerte.

**Comment by wol-soft** [comment]
Danke für den Report. Die Logik des Upgrades sollte so ausgelegt sein, dass die Produktion der Extensions verdoppelt wird (was sie auch aktuell wird), allerdings der Verbrauch nicht erhöht wird (was auch aus der Consumes/Produces Tabelle hervorgeht). Ich habe den Materialcheck auch entsprechend entwickelt, dass für "einfachen" Materialverbrauch bei doppelter Produktion gecheckt wird und sich daraus die produzierte Menge errechnet. Beim Abziehen der Materialien aus dem internen Storage der Extensions werden aktuell trotzdem die Materialien entsprechend der doppelten Produktion, also mit dem bisherigen Faktor, verrechnet.

Ich fixe es mit der kommenden Version. Vielleicht noch heute Abend, ansonsten Anfang kommender Woche.

**Comment by wol-soft** [comment]
1.45.0 ist releast

**Comment by sirtapps** [comment]
Ich habe noch ein weiteres Problem mit negativem Material. :|
![grafik](https://user-images.githubusercontent.com/21241313/60380709-32ad8200-9a4a-11e9-9914-76dcd93555d6.png)

Die Extension sollte fertig gebaut sein. Der negative Wert verringer sich, Richtung Null, entsprechend meiner Tool-Produktion.
