### ISSUE TITLE
Negativer Warenbestand bei Gebäuden

### ISSUE THREAD

**Issue by sirtapps** [wol-soft/beerplop-issues#24]
Ich habe noch ein weiteres Problem mit negativem Material.
![grafik](https://user-images.githubusercontent.com/21241313/60422230-da15ea80-9beb-11e9-8a4f-fb6574bdadeb.png)

Die Extension sollte fertig gebaut sein. Der negative Wert verringert sich, Richtung Null, entsprechend meiner Tool-Produktion.

**Comment by wol-soft** [comment]
Ist der Negative Wert aufgetreten, nachdem die 4,7 Million Tools erreicht wurden? Pausiere die Tool-Zulieferung am besten, bis ich den Bug gefixt habe, um keine weiteren Tools zu verlieren.

**Comment by sirtapps** [comment]
Ja, der Wert ist aufgetreten, nachdem die 4.7 Mio Tools erreicht wurden.

**Comment by wol-soft** [comment]
@sirtapps In der gerade releasten Version 1.46.0 habe ich weitere Checks eingebaut, die einen negativen Fortschritt verhindern. Zusätzlich wird beim Laden der neuen Version einmal geprüft, ob ein negativer Fortschritt vorhanden ist, wenn ja wird dieser korrigiert.

Wenn es korrigiert wurde, kann der Issue geschlossen werden.

**Comment by sirtapps** [comment]
Eine Sache habe ich noch manchmal. Ich weiß aber nicht, wann sie auftritt. Das kann alle Rohstoffe betreffen.

![grafik](https://user-images.githubusercontent.com/21241313/61108409-85dbf780-a482-11e9-9638-8fd378593c43.png)

Tut mir leid, dass ich immer nerve ;)

**Comment by wol-soft** [comment]
Moin @sirtapps 

Das ist ja kein nerven, das ist wichtiges Feedback. Bei dem Feature-Umfang ist es schwierig, alles selbst zu sehen, von daher: ruhig immer weiter issues öffnen.

Aus dem "Mehr Materialien im Lager als Kapazität" habe ich einen neuen Issue gemacht.

Diesen Issue schließe ich dann jetzt, der Bug ist ja behoben.

Danke noch mal für die Issues. Wie gesagt: Das ist wichtiges Feedback.
