### ISSUE TITLE
Enchantments können mit schnellem Doppelklick zweimal ge-sacrifice-t werden

### ISSUE THREAD

**Issue by 2ndK16** [wol-soft/beerplop-issues#25]
Wenn ich in der Enchantment-Übersicht sehr schnell mehrmals auf "Sacrifice" klicke und dasselbe beim Confirm-Dialog wiederhole, kann es passieren, dass zwei Sacrifices zum Preis von einem durchgeführt werden.

**Comment by wol-soft** [comment]
Ich disable das Sacrificen jetzt nach dem ersten Durchlauf, ein zweites Sacrifice wird dementsprechend nicht durchlaufen.
