### ISSUE TITLE
Buff Bottle für Factories

### ISSUE THREAD

**Issue by 2ndK16** [wol-soft/beerplop-issues#26]
Vorschlag: eine Buff Bottle, die die Beer Factories boostet.

**Comment by wol-soft** [comment]
1.47.0 enthält eine neue Buff Bottle, die die Beer Factory Produktion boostet vergleichbar mit Assembly Lines.

**Comment by stefros1l** [comment]
na toll wollte das gleiche Feature gerade vorschlagen :D
