### ISSUE TITLE
Buff Bottle for Magicans

### ISSUE THREAD

**Issue by KingKatzi** [wol-soft/beerplop-issues#28]

**Comment by KingKatzi** [comment]
Vorschlag: eine Buff Bottle, die die Magier boostet.

**Comment by KingKatzi** [comment]
Also noch mehr, als die normale Mana Boost Bottle

**Comment by wol-soft** [comment]
Inwiefern noch mehr?

**Comment by 2ndK16** [comment]
Idee: Training läuft für eine kurze Zeit doppelt oder zehnmal oder x-mal so schnell

**Comment by wol-soft** [comment]
Eine etwas verständlichere Berechnung als "Die Zeit verläuft schneller" wäre es vielleicht zu sagen: Verbleibende Trainingszeiten um 10%, 15% oä. gekürzt.

Noch eine alternative Buff-Bottle könnte einem direkt Mana geben. Da weiß ich aber nicht, ob das so cool ist.

**Comment by KingKatzi** [comment]
Mana Chain :D Ne, ich bin Anti Mana Chain

**Comment by wol-soft** [comment]
1.47.0 enthält eine neue Buff Bottle, die die Trainings verkürzt.
