### ISSUE TITLE
Notifications der Magier überlagern alles

### ISSUE THREAD

**Issue by KingKatzi** [wol-soft/beerplop-issues#29]
Wenn ganz viele Notifications zu den Magiern angezeigt werden, überlagern die alle anderen Elemente, sogar die Buff Bottles, das ist etwas unpraktisch, wenn dann gerade eine Buff Bottle kommt, die man nicht klicken kann

**Comment by wol-soft** [comment]
Da die Magier generell (gerade im Vergleich zu sonstigen Features) sehr viele Notifications erzeugen, wäre noch eine Idee, die Nachrichten zu gruppieren, wenn mehrere parallel auftreten um es so etwas zu entspannen. In etwa sowas wie:

> *Harald* and 13 other magicians started the training of Darkness

> *Harald* and 27 other magicians have finished their training sessions

**Comment by wol-soft** [comment]
Zum Thema "Elemente daneben nicht klickbar" s. https://github.com/FezVrasta/snackbarjs/pull/58

Ich habe das provisorisch als Library-Adjustment schon mal in Beerplop aufgenommen.

An der Gruppierung arbeite ich auch.

**Comment by wol-soft** [comment]
1.52.0 releast mit den Anpassungen, dass benachbarte Elemente klickbar sind sowie der Gruppierung gleicher Magier-Notifications.

Bei der Gruppierung gilt: Es werden die Notifications gruppiert (jeweils aufgeteilt nach Trainings gestartet und Trainings beendet), die in einer Iteration auftreten. Wenn also in mehreren Iterationen nacheinander Notifications ausgegeben werden, weil sich an den Trainings etwas geändert hat, so werden dafür jeweils separate (dann potentiell innerhalb jeder Iteration gruppierte) Notifications angezeigt.
