### ISSUE TITLE
Stock market Autoplops springen bei Änderung

### ISSUE THREAD

**Issue by papulla** [wol-soft/beerplop-issues#3]
Sowohl in der Maske zum Stock Market, wenn man die stocks schließen möchte oder wenn man holds kaufen möchte, springen die Buttons andauernd hoch und runter, bei Änderungen der Plops. Das ist sehr störend, wenn man die schnell kaufen bzw. verkaufen möchte.

**Comment by wol-soft** [comment]
Changed the layout of the fast overview to a fixed table row height:

![image](https://user-images.githubusercontent.com/14750468/59377107-d3fdbe00-8d51-11e9-8860-9375dc78ca90.png)

Changed the layout of the purchase overview for large numbers and a non-breaking layout.

Will be released with version 1.40.0
