### ISSUE TITLE
[Beer Factories] Suggestion: Collapsible Build Queue Entries

### ISSUE THREAD

**Issue by 2ndK16** [wol-soft/beerplop-issues#33]
Rearranging Build Queue jobs via drag'n'drop can be quite a chore because of the slow scrolling. This would be easier if the jobs were collapsible, displaying only the title, progress and buttons but not materials and runtime.

**Comment by wol-soft** [comment]
Released with version 1.51.0. Joby are collapsible by clicking the title of the job (also added an indicating icon)
