### ISSUE TITLE
Lagerkapazität überschritten & Lagermenge passt nicht

### ISSUE THREAD

**Issue by sirtapps** [wol-soft/beerplop-issues#34]
![grafik](https://user-images.githubusercontent.com/21241313/61221984-049e9200-a71a-11e9-847c-a6fc2a2b42d1.png)

Ich habe das Update 1.48.1 am laufen. Der Screenshot entstand, nachdem die Bottle abgelaufen ist.

Dabei fiel mir auch auf, dass die Gesamtlagermenge nicht der Summe entspricht. (70 Mio + 300 Mio + 600 Mio +300 Mio + 400 Mio +3*220 Mio ~ 2.5 Mrd. / Billion, aber nicht 5 Mrd.

**Comment by wol-soft** [comment]
Hi @sirtapps,

den Fix, den ich für die Werte im Lager gemacht habe, habe ich irgendwie wieder rausgeschmissen oder nicht zu Ende gebaut, keine Ahnung. Jetzt wird auf jeden Fall einmal, nachdem die Buff Bottle abgelaufen ist, geprüft, ob sich zu viele Materialien im Lager befinden. Wenn dem so ist, werden die überschüssigen Materialien verworfen.

Auch die Gesamtanzahl wird nun aus den Materialien im Lager aktualisiert zusammengerechnet und nicht separat mitgerechnet (und im Speicherstand verspeichert). Aktuell wird die Zahl entsprechend nicht wieder korrigiert, sobald sie einmal falsch ist.

1.50 mit dem Fix habe ich gerade releast.
