### ISSUE TITLE
Der 'Upgrade' Button ausgrauen, wenn nicht genug Beers

### ISSUE THREAD

**Issue by KingKatzi** [wol-soft/beerplop-issues#35]
Der 'Upgrade' Button bei der Bar könnte ausgegraut/ inaktiv sein, wenn man nicht genug Beers hat, um eine Bar/ Pipeline etc. zu upgraden

**Comment by wol-soft** [comment]
1.50.0 wurde gerade releast mit dem Ausgrauen des Buttons äquivalent zu den anderen Level-Up Buttons.
