### ISSUE TITLE
Building Slots for Bottle Cap Factorys

### ISSUE THREAD

**Issue by Marcnesium87** [wol-soft/beerplop-issues#38]
What about the Idea, that we can construct Slots for Upgrades. Would like to have Amalyse, Enzyme and maybe Fermentation on Cap Factory. We can have an Idle System on our Factorys but not on Bottle Caps.

**Comment by wol-soft** [comment]
I thought this feature request would come up earlier. Have thought about it a few weeks ago and also think it should be possible with a reduced set of equippable items.

**Comment by wol-soft** [comment]
Feature added with version 1.56.0 limited to the equipment of

- Hydrolysis (+15% bottle cap production)
- Fermentation (+30% bottle cap production)
- Degradation (boosting the duration of Bottle Cap Storms)
- Amylase (Auto level up)
- Diastatic Enzyme (Auto purchase Bottle Cap factories)
