### ISSUE TITLE
Autocloning

### ISSUE THREAD

**Issue by Marcnesium87** [wol-soft/beerplop-issues#40]
Do you Guys know the Unique Building "The Clonewars Cloner"? With this Unique Building you unlock the Ability to set the Cloning Area to automation. Now the Cloning ist activated on an random Factory when the needed Building Amount is reacht and the Cloning Cooldown is Zero. Cool Cloning huh?
"This is not Implementet in the Game and just an Suggestion"

**Comment by wol-soft** [comment]
Hi @Marcnesium87, the automated cloning is a feature which definitely is required in a later stage of the game when more and more features are automated (eg. currently working on slots for Bottle Cap factories to provide autobuyer and auto level up there [#38](https://github.com/wol-soft/beerplop-issues/issues/38)).

Currently the cloning and the Beer Factories are decoupled, there is no defined way in which order the features are unlocked. I like the idea of adding additional Unique Builds but I don't like the idea of an Unique Build affecting another Minigame and mixing them up. The Unique Builds should either affect the basic main game (as the currently available buffs for Giza) or unlock something inside the Beer Factories scope.

Instead I think a Holy Upgrade to unlock autocloning would fit better.

**Comment by wol-soft** [comment]
The auto cloning will be available via a holy upgrade. After unlocking the holy upgrade the automation can be enabled/disabled via a simple switch. Each building can be configured with a cloning-priority value to control the order of the clonings.

**Comment by wol-soft** [comment]
Resleased with version 1.58.0
