### ISSUE TITLE
Beer Factory upgrades

### ISSUE THREAD

**Issue by SquaredGrunt** [wol-soft/beerplop-issues#42]
It would be nice if we could see the beer factories upgrades already built.

**Comment by wol-soft** [comment]
@SquaredGrunt you mean instead of the label **Upgrade path locked** which is currently displayed if an upgrade is under construction in the build queue?

**Comment by SquaredGrunt** [comment]
Yes it could be there. One upgrade per line, with a tooltip describing each upgrade ?

**Comment by wol-soft** [comment]
Ok, now i got the issue.

**Comment by wol-soft** [comment]
Implemented with 1.55.0

**Comment by SquaredGrunt** [comment]
> Implemented with 1.55.0

And it's great !

**Comment by wol-soft** [comment]
@SquaredGrunt thanks!
