### ISSUE TITLE
Beerwarts, Beer Bank Banker | Errors when using double quotes in custom name

### ISSUE THREAD

**Issue by wol-soft** [wol-soft/beerplop-issues#45]
If using a double quote in custom names the part after the first double quote will be removed if editing the name again.

If naming a Beer Bank Banker with a double quote and opening the modal for the Beer Bank Banker's training session afterwards, this results in an undefined label:

![image](https://user-images.githubusercontent.com/14750468/62247843-fec9d180-b3e6-11e9-8e87-5944e3024ea7.png)

**Comment by 2ndK16** [comment]
What if I call a banker [Robert"); DROP TABLE STUDENTS; --](https://www.xkcd.com/327/)?

**Comment by wol-soft** [comment]
@2ndK16 nothing. The value just isn't handled properly during HTML templating.

**Comment by wol-soft** [comment]
Named trading routes are also affected

**Comment by wol-soft** [comment]
Fixed
