### ISSUE TITLE
Beer Factories –New building type "The Back Room"

### ISSUE THREAD

**Issue by 2ndK16** [wol-soft/beerplop-issues#46]
The best deals are made in shady back rooms. Players can build back rooms where even shadier lobbyists negotiate subventions for certain industries with the government.
The idea: you build back rooms and can select one (or maybe, after an upgrade, multiple) material(s), the production of which is then government-subsidied, i.e. gets boosted. Maybe, if you have n back rooms, the multiplier could be something like 1+(0.1n).

**Comment by wol-soft** [comment]
So it's more a supporting factory, not a producing factory, similar to the workers lodge if I understand it right.

Maybe it could be something like: each constructed back room boosts by 1% (possible an upgradable value?). One upgrade path provides the selection which producing factory is boosted (can be selected after each upgrade of the path is completed).

As an example: 5 constructed back rooms, the described upgrade path has been finished twice with Lumberjack and Precious Mine selected. This results in a 5% Lumberjack boost and a 5% Precious Mine boost.

Open questions would be:

-  What about the Factory Extensions (in the example case the Charcoal Burner and the Medallion Smith), are they also boosted by 5% each?
- What about proxy factory extensions? Currently they inherit the production capacity of the mirrored extension, consequently they should be also boosted if the factory extensions inherit the back room boost from the base factory.
- Which features/mechanics does the second upgrade path provide?
- Requirements for unlocking the back room

**Comment by 2ndK16** [comment]
It's more similar to the trading routes: you can unlock a certain amount of routes/lobbyists via one upgrade path and then decide which materials you'd like to trade/lobby for. This boost would not apply for a factory or a factory extension but for a material. Say you're producing 100 medaillons per second - the lobbyist would boost this to 105.
The second upgrade path could increase the back rooms' boost up to 10, 15, 20 percent.
I'd unlock the back room after maybe5 trading posts.

**Comment by wol-soft** [comment]
@2ndK16 ok in this scenario the Back Room would behave like the Queue Control or the Engineers where you can't construct the building (eg. for Trading Posts you can keep on going to construct further Trading Posts to increase the max. amount of tradable values on each route) but instead "only" upgrade paths are provided with the functionality you described?

Maybe it could be combined with my example from above where the Back Room is a constructable building. Possible mechanics:

- Each constructed Back Room provides a 1% base-boost for the lobbyists.
- The first upgrade path unlocks lobbyists as you described (consequently keep on going to construct further Back Rooms without 'exploring' the first upgrade path wouldn't have any effect)
- The second upgrade path boosts the base-boost calculated from the amount of constructed Back Rooms for example by 10%

So for example you have constructed 5 Back Rooms and the second upgrade path on Level I (--> 5% boost) your lobbyists would boost the selected materials by (5 * 1%) * 1.1 resulting in a 5.5% boost.

If you have constructed 12 Back Rooms and the second Upgrade Path on level III (eg. a new level unlocks every 4 Back Rooms) your lobbyists would boost the material production by (12 * 1%) * 1.1³ resulting in a ~16% boost

I think designing it as a constructable building gives more flexibility to the player how many resources he want's to invest into the Back Rooms to boost the production (including possible calculations of "Return on Investment" values for the hardcore player 😄)

**Comment by wol-soft** [comment]
Implemented with 1.61.0
