### ISSUE TITLE
Scroll reset after upgrade

### ISSUE THREAD

**Issue by Jared87** [wol-soft/beerplop-issues#48]
While upgrading bar elements below the viewport in the bar minigame the viewport scrolls to the top when clicking on upgrade.

**Comment by wol-soft** [comment]
Currently the scrolling resets after multiple actions

- upgrading
- purchsing a new item
- moving an item
- selling an item
- purchasing a total boost adding upgrade

**Comment by wol-soft** [comment]
Fixed with version 1.56.0
