### ISSUE TITLE
Auto Cloning 

### ISSUE THREAD

**Issue by sirtapps** [wol-soft/beerplop-issues#61]
Es gibt irgendwie eine Unstimmigkeit beim Auto-Cloning.

Manuell geht es scheinbar in 250er Schritten, also 1250 enstspricht 5 Clones, 1000 entspricht 4.
Ich habe 1440 Opener, aber 6 Clones. Bei allen anderen Gebäuden sind es 5 Clones, auch mit 1410 Dispenser oder 1158 Beer Teleporter.

Beim Ausschalten von Auto-Cloning kann ich aktuell nichts weiter clonen.

![grafik](https://user-images.githubusercontent.com/21241313/63510053-e62c7300-c4dd-11e9-85b4-6f4d0cf70d28.png)

**Comment by wol-soft** [comment]
Hi @sirtapps Ich habe es mir gerade einmal angeschaut, war bisher aber leider nicht in der Lage, den Fehler zu reproduzieren. Sind bei dir alle Gebäude zum rechnerischen Maximum, die 250er Schritte sind dafür die korrekte Berechnung, gecloned?

**Comment by sirtapps** [comment]
Servus. Ich habe **ein** Gebäude "geopfert", wobei dann bei **allen** Gebäuden 1 Stufe Cloning entstanden ist.  (Vielleicht täusche ich mich da, aber nach einem Neustart sind alle Gebäude bei mir auf Stufe 1 geclont).

Auf deine Frage: Nein, dass stimmt bei mir irgendwie überhaupt nicht. Ich habe 1514 Dispenser, aber 7 Clonings, 1538 Opener mit 6 Clonings, 1489 Service Assistens mit 6 Clonings....

**Comment by wol-soft** [comment]
Hi @sirtapps was genau meinst du mit **ein** Gebäude "geopfert"?

Die Mechanik soll so funktionieren, dass man beim Sacrifice (wobei man aber ja alle Gebäude "opfert"), für jedes Gebäude die erste Cloning-Stufe bekommt. Also genau das von dir beschriebene Verhalten. Dafür ist es auch nicht relevant, dass bereits 250 von den Gebäuden im Besitz sind. Die zweite Cloning-Stufe schaltet sich dann erst bei 500 Gebäuden frei.

Die Opener haben bei dir dann ja entsprechend die korrekte Cloning-Anzahl. Dispenser und Service Assistants haben eine Cloning-Stufe zu viel. Ich konnte es bislang leider immer noch nicht reproduzieren. Hast du noch irgendwelche besonderen Einstellungen an den Gebäuden vorgenommen? Cloning deaktiviert, wieder aktiviert oä?

**Comment by sirtapps** [comment]
Ich meinte ein Gebäudetyp. Also nicht ein einzelnes Gebäude.

Ich habe heute mal neu gestartet. Folgende Beobachtung:
Sacrifize all 9:52 Uhr (**auto-level up & auto-Buy ausgeschalten**)
	• Alle gleiche Prio, 1x Opener "direkt" geclont (alle 1x Clone, Opener 2x)
	• 10:24 - Cloner 3x, Rest 1x
	• 10:52 - Cloner 4x, Rest 1x
	• 11:24 - Cloner 4x, Dispenser 2x, Rest 1x (keine 1250 Opener gehabt)
	• 13:11 - Cloner 4x, Dispenser 4x, Service 2x, Rest 1x
	• 13:22 - Cloner 4x, Dispenser 4x, Service 3x, Rest 1x
	• 14:08 - alle Updates gekauft und **Auto-Buyer angeschalten** (4x, 4x, 3x, 2x, Rest 1x)
	• 14:47 - **6x Opener (1469), 6x Dispenser(1444)**, 3x Service, 2x Automated, Rest 1x

Bis 14:08 Uhr sieht alles passend aus. Danach ist irgendwie was schief gegangen. Ich habe das Update zwischen 14:08 und 14:47 nicht gesehen, weshalb ich da keine weitere Idee habe.
Cloning war die ganze Zeit aktiv, ohne Änderung. Die Auto-Buyer habe ich erst ausgeschalten gehabt und dann wieder eingeschalten gehabt. Die +2% Updates skalieren ja scheinbar mit dem Plops pro Sekunde, weshalb ich das ausgeschalten habe.

**Comment by sirtapps** [comment]
Jetzt war ich mal bei einem Clonevorgang zufällig dabei....

![grafik](https://user-images.githubusercontent.com/21241313/64026097-67b77d00-cb3e-11e9-9b34-91b77aa29a3d.png)

**Comment by wol-soft** [comment]
Hi @sirtapps danke für die sehr ausführliche Beschreibung! Es liegt wohl an der Kombination Auto-Buyer aktiv und Auto-Cloning aktiv. Ich habe mit 1.60.4 weitere Checks implementiert.

Wäre super, wenn du es nach deinem nächsten "Sacrifice all" noch einmal beobachten könntest.

**Comment by sirtapps** [comment]
Servus @wol-soft, ich hatte gerade ein Gebäude auf 1500 geupdatet, welches 5 Clonings hatte. Hat jetzt 6. Sieht erstmal so aus, dass die Checks aus 1.60.4 passen! :thumbsup:

**Comment by wol-soft** [comment]
Und an dem entsprechenden Gebäude war auch ein Auto-Buyer aktiv?

**Comment by sirtapps** [comment]
Nein, ich hatte das vorher global ausgeschalten gehabt. Ansich hätte das Gebäude einen gehabt.

**Comment by wol-soft** [comment]
Der Fehler scheint nur bei aktiviertem Auto-Buyer aufzutreten. darum passte bei deiner ausführlichen Beschreibung bis 14:08 auch alles.

**Comment by sirtapps** [comment]
Ich hatte jetzt ein Update von 5 auf 6 Clonings, alles mit Auto-Buyer. Mit dem Fehler wäre normalerweise 7 herausgekommen. Ich denke, die Lösung passt!

**Comment by wol-soft** [comment]
Sehr schön, dann schließe ich den Issue mit dem kommenden Release. Sollte es doch noch wieder auftreten einfach wieder aufmachen 👍
