### ISSUE TITLE
Save States window broken in 1.59.0

### ISSUE THREAD

**Issue by ghysler** [wol-soft/beerplop-issues#63]
See attached screenshot. In version 1.59.0 the Save States window shows a login prompt, although I am logged in with my account. Already tried to delete cookies/cache, but that doesn't help.

Running on Chromium Version 76.0.3809.100 (Official Build) (64-bit)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

![Capture](https://user-images.githubusercontent.com/16139880/63605108-94631600-c5cd-11e9-936a-a0d071a6e4f6.PNG)

**Comment by wol-soft** [comment]
Hi @ghysler, I've released a fix fo this one, thanks for the report.

Additionally some translations from the login modal are missing, I'll have a look into it tomorrow.

**Comment by ghysler** [comment]
Save States window indeed working again. Thanks for the quick fix!

**Comment by wol-soft** [comment]
Thanks for checking it.
