### ISSUE TITLE
Unable to locate cloning automation

### ISSUE THREAD

**Issue by ghysler** [wol-soft/beerplop-issues#65]
Version 1.58.0 mentions adding cloning automation. I expected this to be a holy upgrade, but I can't find it anywhere. Am I looking in the wrong place?

**Comment by wol-soft** [comment]
@ghysler maybe you haven't yet unlocked all previously required holy upgrades on the path?

![image](https://user-images.githubusercontent.com/14750468/63619813-ff254900-c5ef-11e9-8b56-4b3749bb697f.png)

**Comment by ghysler** [comment]
Ahh, you're right! In that case I have a long way to go :-)

Could you add this holy upgrade to the wiki page? https://wol-soft.de/apps/beerplop/wiki/index.php/Holy_Upgrades

**Comment by wol-soft** [comment]
Yeah, I'll add it tomorrow. Sorry for the path spoiler 😃

**Comment by wol-soft** [comment]
Added to the documentation at https://wol-soft.de/apps/beerplop/wiki/index.php/Holy_Upgrades
