### ISSUE TITLE
Achievement "Boeing Everett Factory" not achieveable

### ISSUE THREAD

**Issue by ghysler** [wol-soft/beerplop-issues#66]
Might as well report another small issue, while I'm at it :)

The custom buy charge does not allow an amount above 500, which makes it impossible to get the achievement "Boeing Everett Factory" (requires 600).

My suggestion would be to increase the custom buy charge limit to allow a maximum of 600 buys.
EDIT: Or perhaps even a limit of, let's say: 1000? That would allow for challenging additional achievements as well.

**Comment by wol-soft** [comment]
Hi @ghysler thanks for contributing.
This achievement indeed is reachable. Just not with the custom buy charge. You can instead use the **buy max** charge setting to purchase more than 500 buildings with a single click.
