### ISSUE TITLE
Enchantings bei einem Building zurücksetzen

### ISSUE THREAD

**Issue by papulla** [wol-soft/beerplop-issues#7]
Es soll möglich sein, das Enchanting bei einem Building zurück zu setzen.
Da kann man auch ruhig alle seine Mana's verlieren oder nur 50 % zurück erhalten.

**Comment by wol-soft** [comment]
@papulla welchen Zweck soll das Zurücksetzen erfüllen? Denkst du da an einen Sacrify-Mechanismus, der im Anschluss zB. die Enchantments etwas teurer macht (da man sich ja eh recht schnell wieder in ähnliche Anzahlen an Enchantments begeben kann wie man zuvor hatte durch die Preissteigerung) und dafür die Enchantments stärker macht?

Oder einfach nur für eine Neuverteilung?

Wobei ich so beim drüber Nachdenken sagen muss, dass mir der Sacrify-Mechanismus-Gedanke ganz gut gefällt.

**Comment by papulla** [comment]
Ich dachte eher tatsächlich auf komplett zurücksetzen, um die Werte neu zu verteilen, da man ggf. andere Attribute neu setzen möchte wegen der Verteuerung.

**Comment by wol-soft** [comment]
1.45.0 ist releast mit der Möglichkeit, die Enchantments an einem Building zu sacrificen.
