### ISSUE TITLE
Beer Bar | Sticky Menü auf der rechten Seite

### ISSUE THREAD

**Issue by papulla** [wol-soft/beerplop-issues#8]
Bei einem Level ab V wird die rechte Menübar für ein Item nicht mehr Sichtbar, wenn man eine ganz unten ausgewählt hat.
Hier wäre ein Sticky Menü cool.

**Comment by wol-soft** [comment]
@papulla kannst du einen Screenshot hinzufügen? Verstehe die Beschreibung nicht so ganz

**Comment by papulla** [comment]
![image](https://user-images.githubusercontent.com/51719679/59436181-63a57a00-8def-11e9-8886-453f0e9504ed.png)

**Comment by papulla** [comment]
Muss nun für upgrades extra hochscrollen, voll nervig wenn man mehrere items kauft und upgraden möchte

**Comment by wol-soft** [comment]
ah ok, so ein scrollen. Problem verstanden!

**Comment by wol-soft** [comment]
Scrollen der Bereiche mit 1.51.0 entkoppelt
